import fs from 'fs'
import path from 'path'
import { describe, expect, it } from 'vitest'
import {
  APP_HARMONY_CLI_ARTIFACTS,
  isOpenHarmonyProjectDir,
  missingArtifacts,
} from '../scripts/harmony-artifacts.mjs'

const root = path.resolve(import.meta.dirname, '..')
const cliOutDir = path.join(root, 'dist/build/app-harmony')

describe('app-harmony CLI build artifacts', () => {
  it('defines required uni-app harmony shell files', () => {
    expect(APP_HARMONY_CLI_ARTIFACTS).toContain(
      'dist/build/app-harmony/manifest.json'
    )
    expect(APP_HARMONY_CLI_ARTIFACTS).toContain(
      'dist/build/app-harmony/app-service.js'
    )
    expect(APP_HARMONY_CLI_ARTIFACTS).toContain(
      'dist/build/app-harmony/pages/login/login.css'
    )
    expect(APP_HARMONY_CLI_ARTIFACTS).toContain(
      'dist/build/app-harmony/pages/register/register.css'
    )
    expect(APP_HARMONY_CLI_ARTIFACTS).toContain(
      'dist/build/app-harmony/pages/index/index.css'
    )
  })

  it('reports CLI output is not a DevEco OpenHarmony project root', () => {
    if (!fs.existsSync(cliOutDir)) return
    expect(isOpenHarmonyProjectDir(cliOutDir)).toBe(false)
  })

  it('has all CLI artifacts after app-harmony build', () => {
    if (!fs.existsSync(cliOutDir)) {
      expect.fail(
        'Run npm run build:app-harmony first (or npm run test:app-harmony)'
      )
    }
    const missing = missingArtifacts(root, APP_HARMONY_CLI_ARTIFACTS)
    expect(missing).toEqual([])
  })
})

describe('app-harmony DevEco project (HBuilderX)', () => {
  const devEcoDevDir = path.join(root, 'unpackage/dist/dev/app-harmony')

  it('is a full OpenHarmony project only when generated by HBuilderX', () => {
    if (!fs.existsSync(devEcoDevDir)) return
    expect(isOpenHarmonyProjectDir(devEcoDevDir)).toBe(true)
  })
})
